<img src="<?php echo $photoModel->getImagePath($model['model_id']) ?>"
    onerror="this.onerror=null; this.src='/uploads/default-image.jpg';" class="card-img-top img-fluid" alt="Model Image"
    style="width: 300px; height: 300px;" data-toggle="modal" data-target="#modelModal"
    data-model-id="<?php echo $model['model_id']; ?>" data-model-name="<?php echo $model['name']; ?>"
    data-model-age="<?php echo $model['age']; ?>" data-model-height="<?php echo $model['height']; ?>"
    data-model-weight="<?php echo $model['weight']; ?>" data-model-birthday="<?php echo $model['birthday']; ?>"
    data-model-srcs="<?php echo $photoModel->getAllImagePaths($model['model_id']); ?>"
    data-model-phone="<?php echo $model['phone']; ?>" data-eye-color="<?php echo $eyeColor; ?>"
    data-hair-color="<?php echo $hairColor; ?>" data-talant="<?php echo implode(', ', $talants); ?>"
    data-language="<?php echo implode(', ', $languages) ?>" data-gender="<?php echo $gender; ?>"
    data-city="<?php echo $model['city']; ?>" data-clothes-size="<?php echo $model['clothes_size']; ?>"
    data-shoes-size="<?php echo $model['shoes_size']; ?>" data-jeans-size="<?php echo $model['jeans_size']; ?>"
    data-pants-size="<?php echo $model['pants_size']; ?>" data-note="<?php echo $model['note']; ?>"
    onclick="showModelDetails(this)">