name: Deploy to SFTP Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Composer dependencies
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Deploy file
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  sftp_only: true
                  username: "bgdrag0n"
                  server: "srv.bgdragon.com"
                  port: 20180
                  ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
                  local_path: "./*"
                  remote_path: "www/bgdragon.com"
                  sftpArgs: "-o ConnectTimeout=5"
